

# Generated by: tyk-ci/wf-gen
# Generated on: Tue Mar  8 20:25:55 UTC 2022

# Generation commands:
# ./pr.zsh -p -base TD-879/Sync-releng-templates-master -branch TD-879/Sync-releng-templates-master -title internal: Sync releng templates -repos tyk-identity-broker
# m4 -E -DxREPO=tyk-identity-broker


data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-prod"
    }
  }
}

output "tyk-identity-broker" {
  value = data.terraform_remote_state.integration.outputs.tyk-identity-broker
  description = "ECR creds for tyk-identity-broker repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
