#!/bin/bash

# Generated by: tyk-ci/wf-gen
# Generated on: Fri Jan 14 17:45:41 UTC 2022

# Generation commands:
# ./pr.zsh -base v1.2.2-rc5 -branch v1.2.2-rc5-m4-sync -title sync m4 templates -repos tyk-identity-broker
# m4 -E -DxREPO=tyk-identity-broker


echo "Creating user and group..."
GROUPNAME="tyk"
USERNAME="tyk"

getent group "$GROUPNAME" >/dev/null || groupadd -r "$GROUPNAME"
getent passwd "$USERNAME" >/dev/null || useradd -r -g "$GROUPNAME" -M -s /sbin/nologin -c "Tyk service user" "$USERNAME"

