#!/bin/bash



# Generated by: tyk-ci/wf-gen
# Generated on: Tue Mar  8 20:25:55 UTC 2022

# Generation commands:
# ./pr.zsh -p -base TD-879/Sync-releng-templates-master -branch TD-879/Sync-releng-templates-master -title internal: Sync releng templates -repos tyk-identity-broker
# m4 -E -DxREPO=tyk-identity-broker


echo "Creating user and group..."
GROUPNAME="tyk"
USERNAME="tyk"

getent group "$GROUPNAME" >/dev/null || groupadd -r "$GROUPNAME"
getent passwd "$USERNAME" >/dev/null || useradd -r -g "$GROUPNAME" -M -s /sbin/nologin -c "Tyk service user" "$USERNAME"

