# Generated by: tyk-ci/wf-gen
# Generated on: Fri Jan 14 17:45:41 UTC 2022

# Generation commands:
# ./pr.zsh -base v1.2.2-rc5 -branch v1.2.2-rc5-m4-sync -title sync m4 templates -repos tyk-identity-broker
# m4 -E -DxREPO=tyk-identity-broker


data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-prod"
    }
  }
}

output "tyk-identity-broker" {
  value = data.terraform_remote_state.integration.outputs.tyk-identity-broker
  description = "ECR creds for tyk-identity-broker repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
