#!/bin/sh

# Generated by: tyk-ci/wf-gen
# Generated on: Fri 27 Aug 10:58:02 UTC 2021

# Generation commands:
# ./pr.zsh -title [TT-2932] more control over upgrades -branch releng/upgrades -base master
# m4 -E -DxREPO=tyk-identity-broker


if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-identity-broker.service ]; then
	cp /opt/tyk-identity-broker/install/tyk-identity-broker.service /lib/systemd/system/tyk-identity-broker.service
    fi
fi
