#!/bin/sh

# Generated by: tyk-ci/wf-gen
# Generated on: Thu Jan 27 14:55:58 UTC 2022

# Generation commands:
# ./pr.zsh -p -base master-m4-sync -branch master-m4-sync -title Change commit var to Commit -repos tyk,tyk-pump,tyk-analytics,tyk-identity-broker
# m4 -E -DxREPO=tyk-identity-broker


if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-identity-broker.service ]; then
        cp /opt/tyk-identity-broker/install/inits/systemd/system/tyk-identity-broker.service /lib/systemd/system/tyk-identity-broker.service
    fi
else
    if [ ! -f /etc/init.d/tyk-identity-broker ]; then
        cp /opt/tyk-identity-broker/install/inits/sysv/init.d/tyk-identity-broker /etc/init.d/tyk-identity-broker
    fi
fi
