name: intelligent branch suggestions
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: read

jobs:
  branch-suggestions:
    uses: TykTechnologies/github-actions/.github/workflows/branch-suggestion.yml@TT-15793-implement-intelligent-merge-branches
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}