name: intelligent branch merge suggestion
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: read

jobs:
  branch-suggestions:
    uses: TykTechnologies/github-actions/.github/workflows/branch-suggestion.yml@54f704c6ee86a6d5a85efa914fa3e9fd4e8bd9c9
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}