name: Go Test Workflow

on:
  push:
    branches:
      - master
      - release-**
  pull_request:
    branches:
      - master
      - release-**
env:
  TYK_IB_STORAGE_STORAGETYPE: file
  GO_VERSION: "1.25"

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Tyk Identity Broker
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Fetch base branch
        if: ${{ github.event_name == 'pull_request' }}
        run: git fetch origin ${{ github.base_ref }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9  # v6
        timeout-minutes: 20
        with:
          version: v2.5.0
          only-new-issues: ${{ github.event_name == 'pull_request' }}
          args: --issues-exit-code=0 -v ./...
          skip-cache: false
          skip-save-cache: false

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: golangcilint
          retention-days: 1
          path: |
            golangci-lint-report.json

  ci-test:
    name: "${{ matrix.databases }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        databases:
          - mongo-mgo
          - mongo-official
          - file
        redis-version: [5]
        mongodb-version: [4.2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies and basic hygiene test
        id: hygiene
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Start Redis
        uses: supercharge/redis-github-action@1f58ff85cf4f9ef3c036109c11acd8376b436b47  # 1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@751e4ddb1f8de2717b75f275abce04735664ef46  # 1.2.0
        with:
          mongodb-version: "${{ matrix.mongodb-version }}"

      - name: Run tests
        run: |
          ./bin/ci-tests.sh ${{ matrix.databases }}
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.databases }}
          retention-days: 1
          path: |
            *cov
  sonar-cloud-analysis:
    runs-on: ubuntu-latest
    needs: [ci-test, golangci-lint]
    permissions:
      contents: read
    steps:
      - name: Checkout TIB
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Fetch base branch
        if: ${{ github.event_name == 'pull_request' }}
        run: git fetch origin ${{ github.base_ref }}
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true
      - name: Download golangcilint artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4
        with:
          name: golangcilint
      - name: Check reports existence
        id: check_files
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v3
        with:
          files: 'golangci-lint-report.json'
          fail: true
      - name: Install Dependencies
        run: >
          go install github.com/wadey/gocovmerge@latest

      - name: merge reports
        run: |
          ./bin/merge-cov.sh
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8  # v5.0.0
        with:
          args: >
            -Dsonar.organization=tyktechnologies
            -Dsonar.projectKey=TykTechnologies_tyk-identity-broker
            -Dsonar.sources=.
            -Dsonar.exclusions=ci/**
            -Dsonar.coverage.exclusions=**/*_test.go,**/mocks/*.go
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.tests=.
            -Dsonar.go.coverage.reportPaths=*.cov
            -Dsonar.go.golangci-lint.reportPaths=golangci-lint-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  aggregator-ci-test:
    name: Unit Tests & Linting
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'pull_request' }}
    needs: [ ci-test ]
    steps:
      - name: Aggregate results
        run: |
          failed=()
          # Get the needs context as JSON once
          needs_json='${{ toJSON(needs) }}'
          
          # Loop through all jobs in the needs context
          for job in $(echo "$needs_json" | jq -r 'keys[]'); do
            job_result=$(echo "$needs_json" | jq -r --arg job "$job" '.[$job].result')
          
            if [[ "$job_result" != "success" ]]; then
              failed+=("$job")
            fi
          done
          
          if (( ${#failed[@]} )); then
            # Join the failed job names with commas
            failed_jobs=$(IFS=", "; echo "${failed[*]}")
            echo "❌ Failed jobs ----- : $failed_jobs"
            exit 1
          fi
          
          echo "✅ All required jobs succeeded"

