name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -o myapp

      - name: Run tests
        run: go test ./...

      - name: Download golangcilint artifact
        uses: actions/download-artifact@v2
        with:
          name: golangcilint

      - name: Set up golangcilint
        run: |
          chmod +x golangcilint
          export PATH=$PATH:$PWD

      - name: Lint code
        run: golangcilint ./...

      - name: Deploy
        run: ./deploy.sh
