# yamllint disable rule:line-length rule:truthy
---
name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - master
      - release-**
    tags:
      - 'v*'

jobs:
  release:
    uses: TykTechnologies/github-actions/.github/workflows/release-common.yml@TT-18139-releng-poc
    secrets: inherit
    permissions:
      id-token: write   # AWS OIDC
      contents: read    # actions/checkout
    with:
      repo_name: tyk-identity-broker
      upgrade_repo: tyk-identity-broker
      golang_cross: 1.26-bookworm
      cgo: '0'
      platforms_std: 'linux/amd64,linux/arm64,linux/s390x'
      dockerhub_std: tykio/tyk-identity-broker
      cloudsmith_std: docker.tyk.io/tyk-identity-broker/tyk-identity-broker
      image_title: Tyk Identity Broker
      image_description: Tyk Authentication Proxy for third-party login
      build_fips: false
      run_api_tests: false
